name: Deploy to S3

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload to S3
      uses: adreamer
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: my-awesome-jikoshoukai 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-1
        SOURCE_DIR: "./"
